on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
  NPM_TOKEN: ${{ secrets.NPM_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.8.0
      - name: Install
        run: npm install
      - name: Bootstrap
        run: npm run lerna:bootstrap
      - name: Build
        run: npm run build
      - name: NPM publish
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm run lerna:publish:ci
